package view;

import Connectivity.Dbmanager;
import Connectivity.QueryManager;
import java.awt.Color;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.DefaultListModel;
import model.Baggage;
import model.CreateAccount;
import model.Customerinfo;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author JasperKapper >= Kavehskapper
 */
public class Admin extends javax.swing.JFrame {

    private ArrayList<CreateAccount> udl = new ArrayList();
    private int userId = 0;

    int xMouse, yMouse;
 public void SetInfo(CreateAccount createaccount) {
        Name.setText("Logged in as: " +createaccount.accounttype);
        usernameAdminText.setText(createaccount.username);
        welcomeAdmin.setText("Welcome " + createaccount.username+ "," );
        nameAdminText.setText("Not Set");
        usernameAdminText.setText("Not Set");
        addressAdminText.setText("Not Set");
        dateAdminText.setText("Not Set");
        postalcodeAdminText.setText("Not Set");
        cityAdminText.setText("Not Set");
        emailAdminText.setText("Not Set");
 }
    
    public void SetUser(CreateAccount createaccount) {

        if ("admin".equals(createaccount.accounttype)) {
            setVisible(true);
        } else {
            setVisible(false);
        }
    }

    public Admin() {
        super("Lost Baggage");
        setSize(1300, 650);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        initComponents();

        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(AdminHome);
        jPanel1.repaint();
        jPanel1.revalidate();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel18 = new javax.swing.JLabel();
        Name = new javax.swing.JLabel();
        ID = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        AdminHome = new javax.swing.JPanel();
        welcomeAdmin = new javax.swing.JLabel();
        profileAdmin = new javax.swing.JLabel();
        nameAdmin = new javax.swing.JLabel();
        nameAdminText = new javax.swing.JLabel();
        usernameAdmin = new javax.swing.JLabel();
        usernameAdminText = new javax.swing.JLabel();
        addressAdmin = new javax.swing.JLabel();
        addressAdminText = new javax.swing.JLabel();
        dateAdmin = new javax.swing.JLabel();
        dateAdminText = new javax.swing.JLabel();
        cityAdmin = new javax.swing.JLabel();
        cityAdminText = new javax.swing.JLabel();
        postalcodeAdmin = new javax.swing.JLabel();
        postalcodeAdminText = new javax.swing.JLabel();
        countryAdmin = new javax.swing.JLabel();
        countryAdminText = new javax.swing.JLabel();
        emailAdmin = new javax.swing.JLabel();
        emailAdminText = new javax.swing.JLabel();
        editAdminButton = new javax.swing.JToggleButton();
        BackgroundAdmin = new javax.swing.JLabel();
        Edit = new javax.swing.JPanel();
        adminEdit = new javax.swing.JPanel();
        corendonEdit = new javax.swing.JLabel();
        accountinfoEdit = new javax.swing.JLabel();
        personalInfoEdit = new javax.swing.JLabel();
        newusernameEdit = new javax.swing.JLabel();
        newusernameEditText = new javax.swing.JTextField();
        oldpasswordEdit = new javax.swing.JLabel();
        oldpasswordEditText = new javax.swing.JTextField();
        newpasswordEdit = new javax.swing.JLabel();
        newpasswordEditText = new javax.swing.JTextField();
        repeatpasswordEdit = new javax.swing.JLabel();
        repeatpasswordEditText = new javax.swing.JTextField();
        accountypeEdit = new javax.swing.JLabel();
        accounttypeDropboxEdit = new javax.swing.JComboBox();
        nameEdit = new javax.swing.JLabel();
        nameEditText = new javax.swing.JTextField();
        addressEdit = new javax.swing.JLabel();
        addressEditText = new javax.swing.JTextField();
        cityEdit = new javax.swing.JLabel();
        cityEditText = new javax.swing.JTextField();
        postalcodeEdit = new javax.swing.JLabel();
        postalcodeEditText = new javax.swing.JTextField();
        countryEdit = new javax.swing.JLabel();
        countryEditText = new javax.swing.JTextField();
        emailEdit = new javax.swing.JLabel();
        emailEditText = new javax.swing.JTextField();
        saveEdit = new javax.swing.JButton();
        backgroundEdit = new javax.swing.JLabel();
        adminPersonal = new javax.swing.JPanel();
        corendonPersonal = new javax.swing.JLabel();
        editinfoPersonal = new javax.swing.JLabel();
        usernamePersonal = new javax.swing.JLabel();
        usernamePersonalText = new javax.swing.JTextField();
        passwordPersonal = new javax.swing.JLabel();
        passwordPersonalText = new javax.swing.JTextField();
        accounttypePersonal = new javax.swing.JLabel();
        accounttypePersonalText = new javax.swing.JTextField();
        editPersonalButton = new javax.swing.JButton();
        editPersonalinfoButton = new javax.swing.JButton();
        searchPersonalText = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        listUsers = new javax.swing.JList();
        searchaccountPersonalButton = new javax.swing.JButton();
        selectaccountPersonalButton = new javax.swing.JButton();
        deleteaccountPersonalButton = new javax.swing.JButton();
        backgroundPersonal = new javax.swing.JLabel();
        Create = new javax.swing.JPanel();
        AdminCreate = new javax.swing.JPanel();
        corendonCreate = new javax.swing.JLabel();
        accountinfoCreate = new javax.swing.JLabel();
        personalinfoCreate = new javax.swing.JLabel();
        newusernameCreate = new javax.swing.JLabel();
        newusernameCreateText = new javax.swing.JTextField();
        newpasswordCreate = new javax.swing.JLabel();
        newpasswordCreateText = new javax.swing.JPasswordField();
        repeatpasswordCreate = new javax.swing.JLabel();
        repeatpasswordCreateText = new javax.swing.JPasswordField();
        accounttypeCreate = new javax.swing.JLabel();
        accounttypeCreateText = new javax.swing.JTextField();
        nameCreate = new javax.swing.JLabel();
        nameCreateText = new javax.swing.JTextField();
        addressCreate = new javax.swing.JLabel();
        addressCreateText = new javax.swing.JTextField();
        cityCreate = new javax.swing.JLabel();
        cityCreateText = new javax.swing.JTextField();
        postalcodeCreate = new javax.swing.JLabel();
        postalcodeCreateText = new javax.swing.JTextField();
        countryCreate = new javax.swing.JLabel();
        countryCreateText = new javax.swing.JTextField();
        emailCreate = new javax.swing.JLabel();
        emailCreateText = new javax.swing.JTextField();
        dateofbirthCreate = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        backgroundCreate = new javax.swing.JLabel();
        Help = new javax.swing.JPanel();
        AdminHelp = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel5 = new javax.swing.JLabel();
        Delete = new javax.swing.JPanel();
        AdminDelete = new javax.swing.JPanel();
        corendonDelete = new javax.swing.JLabel();
        accountinfoDelete = new javax.swing.JLabel();
        personalinfoDelete = new javax.swing.JLabel();
        chooseaccountDelete = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        areusureDelete = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        deleteDeleteButton = new javax.swing.JButton();
        nameDelete = new javax.swing.JLabel();
        nameDeleteText = new javax.swing.JTextField();
        addressDelete = new javax.swing.JLabel();
        addressDeleteText = new javax.swing.JTextField();
        cityDelete = new javax.swing.JLabel();
        cityDeleteText = new javax.swing.JTextField();
        postalcodeDelete = new javax.swing.JLabel();
        postalcodeDeleteText = new javax.swing.JTextField();
        countryDelete = new javax.swing.JLabel();
        countryDeleteText = new javax.swing.JTextField();
        emailDelete = new javax.swing.JLabel();
        emailDeleteText = new javax.swing.JTextField();
        backgroundDelete = new javax.swing.JLabel();
        menu1 = new javax.swing.JPanel();
        homeButton1 = new javax.swing.JLabel();
        editButton = new javax.swing.JLabel();
        createButton = new javax.swing.JLabel();
        helpButton = new javax.swing.JLabel();
        logoutKnop = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        jLabel18.setText("Date of birth :");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lost Baggage");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Name.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Name.setText("Logged in as:");
        getContentPane().add(Name, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, 150, 30));

        ID.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        ID.setText("Employee ID:");
        getContentPane().add(ID, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 90, 130, 30));

        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        jPanel1.setLayout(new java.awt.BorderLayout());

        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Home.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminHome.setBackground(new java.awt.Color(153, 51, 51));
        AdminHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        AdminHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeAdmin.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        welcomeAdmin.setText("Welcome, ");
        AdminHome.add(welcomeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 80, 310, 50));

        profileAdmin.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        profileAdmin.setText("Profile :");
        AdminHome.add(profileAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 150, 90, 40));

        nameAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameAdmin.setText("Name :");
        AdminHome.add(nameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, 90, 20));

        nameAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        nameAdminText.setText("example: John");
        AdminHome.add(nameAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 90, 20));

        usernameAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernameAdmin.setText("Username :");
        AdminHome.add(usernameAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 90, 20));

        usernameAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        usernameAdminText.setText("example: JohnS001");
        AdminHome.add(usernameAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 100, 20));

        addressAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressAdmin.setText("Address :");
        AdminHome.add(addressAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 270, 90, 20));

        addressAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        addressAdminText.setText("example: Duivendrechtsekade 44");
        AdminHome.add(addressAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 170, 20));

        dateAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateAdmin.setText("Date :");
        AdminHome.add(dateAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 300, 90, 20));

        dateAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        dateAdminText.setText("example: 01.10.2014");
        AdminHome.add(dateAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 110, 20));

        cityAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityAdmin.setText("City :");
        AdminHome.add(cityAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 210, 90, 20));

        cityAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cityAdminText.setText("example: Amsterdam");
        AdminHome.add(cityAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 210, 110, 20));

        postalcodeAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        postalcodeAdmin.setText("Postal code :");
        AdminHome.add(postalcodeAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 240, 90, 20));

        postalcodeAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        postalcodeAdminText.setText("example: 1096AH");
        AdminHome.add(postalcodeAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 240, 90, 20));

        countryAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countryAdmin.setText("Country :");
        AdminHome.add(countryAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 270, 90, 20));

        countryAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        countryAdminText.setText("example: The Netherlands");
        AdminHome.add(countryAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 270, 130, 20));

        emailAdmin.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailAdmin.setText("Email :");
        AdminHome.add(emailAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 90, 20));

        emailAdminText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        emailAdminText.setText("example: John.S@corendon.nl");
        AdminHome.add(emailAdminText, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, 150, 20));

        editAdminButton.setText("Edit");
        editAdminButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editAdminButtonMouseClicked(evt);
            }
        });
        editAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editAdminButtonActionPerformed(evt);
            }
        });
        AdminHome.add(editAdminButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        BackgroundAdmin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        BackgroundAdmin.setToolTipText("");
        BackgroundAdmin.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminHome.add(BackgroundAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 490));

        Home.add(AdminHome, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(Home, java.awt.BorderLayout.CENTER);

        Edit.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Edit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        adminEdit.setBackground(new java.awt.Color(153, 51, 51));
        adminEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        adminEdit.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        corendonEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        corendonEdit.setText("jLabel11");
        adminEdit.add(corendonEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        accountinfoEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        accountinfoEdit.setText("Account information :");
        adminEdit.add(accountinfoEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        personalInfoEdit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        personalInfoEdit.setText("Personal information :");
        adminEdit.add(personalInfoEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 110, -1, -1));

        newusernameEdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        newusernameEdit.setText("New Username :");
        adminEdit.add(newusernameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 100, 20));

        newusernameEditText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        newusernameEditText.setText("Example: Administrator1988");
        adminEdit.add(newusernameEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 180, 240, -1));

        oldpasswordEdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        oldpasswordEdit.setText("Old Password :");
        adminEdit.add(oldpasswordEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 100, 20));

        oldpasswordEditText.setText("***********");
        oldpasswordEditText.setToolTipText("");
        adminEdit.add(oldpasswordEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, 240, -1));

        newpasswordEdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        newpasswordEdit.setText("New Password :");
        adminEdit.add(newpasswordEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 100, 20));

        newpasswordEditText.setText("***********");
        adminEdit.add(newpasswordEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, 240, -1));

        repeatpasswordEdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        repeatpasswordEdit.setText(" Repeat password :");
        adminEdit.add(repeatpasswordEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 100, 20));

        repeatpasswordEditText.setText("***********");
        adminEdit.add(repeatpasswordEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 240, -1));

        accountypeEdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        accountypeEdit.setText("Account type :");
        adminEdit.add(accountypeEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 300, 100, 20));

        accounttypeDropboxEdit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Manager", "Administrator", "Employee" }));
        adminEdit.add(accounttypeDropboxEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 240, -1));

        nameEdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameEdit.setText("Name :");
        adminEdit.add(nameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 100, 20));

        nameEditText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        nameEditText.setText("example: John");
        adminEdit.add(nameEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 240, -1));

        addressEdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressEdit.setText("Address :");
        adminEdit.add(addressEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, 20));

        addressEditText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        addressEditText.setText("Example: Egidiusstraat");
        addressEditText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressEditTextActionPerformed(evt);
            }
        });
        adminEdit.add(addressEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 240, -1));

        cityEdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityEdit.setText("City :");
        adminEdit.add(cityEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 100, 20));

        cityEditText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cityEditText.setText("Example: Amsterdam");
        adminEdit.add(cityEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 240, -1));

        postalcodeEdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        postalcodeEdit.setText("Postal code :");
        adminEdit.add(postalcodeEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 100, 20));

        postalcodeEditText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        postalcodeEditText.setText("Example: 1055GK");
        adminEdit.add(postalcodeEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 240, -1));

        countryEdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countryEdit.setText("Country :");
        adminEdit.add(countryEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 100, 20));

        countryEditText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        countryEditText.setText("Example: The Netherlands");
        adminEdit.add(countryEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 240, -1));

        emailEdit.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailEdit.setText("Email :");
        adminEdit.add(emailEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 100, 20));

        emailEditText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        emailEditText.setText("Example: John@corendon.com");
        adminEdit.add(emailEditText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 240, -1));

        saveEdit.setText("Save ");
        saveEdit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                saveEditActionPerformed(evt);
            }
        });
        adminEdit.add(saveEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 370, -1, -1));

        backgroundEdit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        backgroundEdit.setToolTipText("");
        backgroundEdit.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        adminEdit.add(backgroundEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        Edit.add(adminEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        adminPersonal.setBackground(new java.awt.Color(153, 51, 51));
        adminPersonal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        adminPersonal.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        corendonPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        corendonPersonal.setText("jLabel11");
        adminPersonal.add(corendonPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        editinfoPersonal.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        editinfoPersonal.setText("Edit account");
        adminPersonal.add(editinfoPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 130, -1, -1));

        usernamePersonal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        usernamePersonal.setText("Username :");
        adminPersonal.add(usernamePersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 100, 20));

        usernamePersonalText.setText("example: John");
        usernamePersonalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                usernamePersonalTextActionPerformed(evt);
            }
        });
        adminPersonal.add(usernamePersonalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 170, 160, -1));

        passwordPersonal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        passwordPersonal.setText("Password :");
        adminPersonal.add(passwordPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 200, 100, 20));

        passwordPersonalText.setText("*******");
        passwordPersonalText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                passwordPersonalTextActionPerformed(evt);
            }
        });
        adminPersonal.add(passwordPersonalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 200, 160, -1));

        accounttypePersonal.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        accounttypePersonal.setText("Accounttype :");
        adminPersonal.add(accounttypePersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 230, 100, 20));

        accounttypePersonalText.setText("example: Manager");
        adminPersonal.add(accounttypePersonalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 230, 160, -1));

        editPersonalButton.setText("Edit");
        editPersonalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editPersonalButtonMouseClicked(evt);
            }
        });
        adminPersonal.add(editPersonalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 270, 60, -1));

        editPersonalinfoButton.setText("Edit Personal information");
        editPersonalinfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editPersonalinfoButtonActionPerformed(evt);
            }
        });
        editPersonalinfoButton.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                editPersonalinfoButtonKeyPressed(evt);
            }
        });
        adminPersonal.add(editPersonalinfoButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 270, 170, -1));

        searchPersonalText.setText("Search...");
        adminPersonal.add(searchPersonalText, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 130, 340, -1));

        jScrollPane2.setToolTipText("");

        jScrollPane2.setViewportView(listUsers);

        adminPersonal.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 160, 340, 120));

        searchaccountPersonalButton.setText("Search account");
        searchaccountPersonalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchaccountPersonalButtonActionPerformed(evt);
            }
        });
        adminPersonal.add(searchaccountPersonalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 300, -1, -1));

        selectaccountPersonalButton.setText("Select account");
        adminPersonal.add(selectaccountPersonalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 300, -1, -1));

        deleteaccountPersonalButton.setText("Delete account");
        deleteaccountPersonalButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deleteaccountPersonalButtonMouseClicked(evt);
            }
        });
        deleteaccountPersonalButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteaccountPersonalButtonActionPerformed(evt);
            }
        });
        adminPersonal.add(deleteaccountPersonalButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(725, 300, -1, -1));

        backgroundPersonal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        backgroundPersonal.setToolTipText("");
        backgroundPersonal.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        adminPersonal.add(backgroundPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        Edit.add(adminPersonal, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(Edit, java.awt.BorderLayout.PAGE_START);

        Create.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Create.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminCreate.setBackground(new java.awt.Color(153, 51, 51));
        AdminCreate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        AdminCreate.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        corendonCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        corendonCreate.setText("jLabel11");
        AdminCreate.add(corendonCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        accountinfoCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        accountinfoCreate.setText("Account information:");
        AdminCreate.add(accountinfoCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        personalinfoCreate.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        personalinfoCreate.setText("Personal information:");
        AdminCreate.add(personalinfoCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 110, -1, -1));

        newusernameCreate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        newusernameCreate.setText("New Username :");
        AdminCreate.add(newusernameCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, 20));

        newusernameCreateText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        newusernameCreateText.setText("Example: Adminstrator1981");
        newusernameCreateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newusernameCreateTextActionPerformed(evt);
            }
        });
        AdminCreate.add(newusernameCreateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 240, -1));

        newpasswordCreate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        newpasswordCreate.setText("New Password :");
        AdminCreate.add(newpasswordCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 100, 20));

        newpasswordCreateText.setText("jPasswordField1");
        newpasswordCreateText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        AdminCreate.add(newpasswordCreateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 240, 20));

        repeatpasswordCreate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        repeatpasswordCreate.setText(" Repeat password :");
        AdminCreate.add(repeatpasswordCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, 100, 20));

        repeatpasswordCreateText.setText("jPasswordField1");
        repeatpasswordCreateText.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));
        repeatpasswordCreateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                repeatpasswordCreateTextActionPerformed(evt);
            }
        });
        AdminCreate.add(repeatpasswordCreateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, 240, 20));

        accounttypeCreate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        accounttypeCreate.setText("Account type :");
        AdminCreate.add(accounttypeCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, 100, 20));

        accounttypeCreateText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        accounttypeCreateText.setText("Manager,Employee,Admin");
        accounttypeCreateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                accounttypeCreateTextActionPerformed(evt);
            }
        });
        AdminCreate.add(accounttypeCreateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 250, 240, -1));

        nameCreate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameCreate.setText("Name :");
        AdminCreate.add(nameCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 100, 20));

        nameCreateText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        nameCreateText.setText("example: john");
        AdminCreate.add(nameCreateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 240, -1));

        addressCreate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressCreate.setText("Address :");
        AdminCreate.add(addressCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, 20));

        addressCreateText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        addressCreateText.setText("Example: Egidiusstraat");
        addressCreateText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressCreateTextActionPerformed(evt);
            }
        });
        AdminCreate.add(addressCreateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 240, -1));

        cityCreate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityCreate.setText("City :");
        AdminCreate.add(cityCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 100, 20));

        cityCreateText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cityCreateText.setText("Example: Amsterdam");
        cityCreateText.setToolTipText("");
        AdminCreate.add(cityCreateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 240, -1));

        postalcodeCreate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        postalcodeCreate.setText("Postal code :");
        AdminCreate.add(postalcodeCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 100, 20));

        postalcodeCreateText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        postalcodeCreateText.setText("Example: 1055GK");
        AdminCreate.add(postalcodeCreateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 240, -1));

        countryCreate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countryCreate.setText("Country :");
        AdminCreate.add(countryCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 100, 20));

        countryCreateText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        countryCreateText.setText("Example: The Netherlands");
        AdminCreate.add(countryCreateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 240, -1));

        emailCreate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailCreate.setText("Email :");
        AdminCreate.add(emailCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 100, 20));

        emailCreateText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        emailCreateText.setText("Example: John@corendon.com");
        AdminCreate.add(emailCreateText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 240, -1));

        dateofbirthCreate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        dateofbirthCreate.setText("Date of birth");
        AdminCreate.add(dateofbirthCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 330, 100, 20));

        jSpinner2.setModel(new javax.swing.SpinnerDateModel(new java.util.Date(), null, null, java.util.Calendar.YEAR));
        AdminCreate.add(jSpinner2, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 330, 150, 20));

        jButton2.setText("Save & Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        AdminCreate.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, -1, -1));

        backgroundCreate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        backgroundCreate.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        backgroundCreate.setToolTipText("");
        backgroundCreate.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminCreate.add(backgroundCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        Create.add(AdminCreate, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(Create, java.awt.BorderLayout.LINE_END);

        Help.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Help.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminHelp.setBackground(new java.awt.Color(153, 51, 51));
        AdminHelp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, java.awt.Color.lightGray));
        AdminHelp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel17.setText("jLabel11");
        AdminHelp.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        AdminHelp.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        jLabel52.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel52.setText("Download PDF: ");
        AdminHelp.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));
        AdminHelp.add(jFileChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, 270));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminHelp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 971, 482));

        Help.add(AdminHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 490));

        jPanel1.add(Help, java.awt.BorderLayout.LINE_START);

        Delete.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Delete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        AdminDelete.setBackground(new java.awt.Color(153, 51, 51));
        AdminDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        AdminDelete.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        corendonDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        corendonDelete.setText("jLabel11");
        AdminDelete.add(corendonDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        accountinfoDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        accountinfoDelete.setText("Account information:");
        AdminDelete.add(accountinfoDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, -1, -1));

        personalinfoDelete.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        personalinfoDelete.setText("Personal information:");
        AdminDelete.add(personalinfoDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 110, -1, -1));

        chooseaccountDelete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        chooseaccountDelete.setText("Choose account :");
        AdminDelete.add(chooseaccountDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 160, 100, 20));

        jSpinner1.setModel(new javax.swing.SpinnerListModel(new String[] {"Admini1994", "Manager001", "James007", "YassineEla"}));
        jSpinner1.setToolTipText("");
        AdminDelete.add(jSpinner1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 160, 110, 30));

        areusureDelete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        areusureDelete.setText("Are u sure :");
        AdminDelete.add(areusureDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 100, 20));

        jCheckBox1.setText("Yes");
        AdminDelete.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, -1));

        deleteDeleteButton.setText("Delete");
        AdminDelete.add(deleteDeleteButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, -1, -1));

        nameDelete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        nameDelete.setText("Name :");
        AdminDelete.add(nameDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, 100, 20));

        nameDeleteText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        nameDeleteText.setText("example: John");
        nameDeleteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameDeleteTextActionPerformed(evt);
            }
        });
        AdminDelete.add(nameDeleteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 150, 240, 20));

        addressDelete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        addressDelete.setText("Address :");
        AdminDelete.add(addressDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, 100, 20));

        addressDeleteText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        addressDeleteText.setText("Example: Egidiusstraat");
        addressDeleteText.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addressDeleteTextActionPerformed(evt);
            }
        });
        AdminDelete.add(addressDeleteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 180, 240, 20));

        cityDelete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        cityDelete.setText("City :");
        AdminDelete.add(cityDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 210, 100, 20));

        cityDeleteText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        cityDeleteText.setText("Example: Amsterdam");
        cityDeleteText.setToolTipText("");
        AdminDelete.add(cityDeleteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 210, 240, 20));

        postalcodeDelete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        postalcodeDelete.setText("Postal code :");
        AdminDelete.add(postalcodeDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, 100, 20));

        postalcodeDeleteText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        postalcodeDeleteText.setText("Example: 1055GK");
        AdminDelete.add(postalcodeDeleteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 240, 240, 20));

        countryDelete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        countryDelete.setText("Country :");
        AdminDelete.add(countryDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 270, 100, 20));

        countryDeleteText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        countryDeleteText.setText("Example: The Netherlands");
        AdminDelete.add(countryDeleteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 270, 240, 20));

        emailDelete.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        emailDelete.setText("Email :");
        AdminDelete.add(emailDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, 100, 20));

        emailDeleteText.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        emailDeleteText.setText("Example: John@corendon.com");
        AdminDelete.add(emailDeleteText, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 300, 240, 20));

        backgroundDelete.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        backgroundDelete.setToolTipText("");
        backgroundDelete.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        AdminDelete.add(backgroundDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 450));

        Delete.add(AdminDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(Delete, java.awt.BorderLayout.CENTER);

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 910, 460));

        menu1.setBackground(new java.awt.Color(255, 255, 255));

        homeButton1.setBackground(new java.awt.Color(255, 255, 255));
        homeButton1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeButton1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeButton1.setText("Home");
        homeButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton1.setOpaque(true);
        homeButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButton1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButton1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButton1MouseExited(evt);
            }
        });

        editButton.setBackground(new java.awt.Color(255, 255, 255));
        editButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        editButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        editButton.setText("Edit account");
        editButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        editButton.setOpaque(true);
        editButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                editButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                editButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                editButtonMouseExited(evt);
            }
        });

        createButton.setBackground(new java.awt.Color(255, 255, 255));
        createButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        createButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        createButton.setText("Create account");
        createButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        createButton.setOpaque(true);
        createButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                createButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                createButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                createButtonMouseExited(evt);
            }
        });

        helpButton.setBackground(new java.awt.Color(255, 255, 255));
        helpButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        helpButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpButton.setText("Help");
        helpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpButton.setOpaque(true);
        helpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpButtonMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menu1Layout = new javax.swing.GroupLayout(menu1);
        menu1.setLayout(menu1Layout);
        menu1Layout.setHorizontalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(editButton, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
            .addComponent(createButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(helpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menu1Layout.setVerticalGroup(
            menu1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menu1Layout.createSequentialGroup()
                .addComponent(homeButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(createButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 201, Short.MAX_VALUE))
        );

        getContentPane().add(menu1, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 180, 178, 410));

        logoutKnop.setBackground(new java.awt.Color(147, 51, 51));
        logoutKnop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutKnop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutKnop.setText("LOGOUT");
        logoutKnop.setOpaque(true);
        logoutKnop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutKnopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutKnopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutKnopMouseExited(evt);
            }
        });
        getContentPane().add(logoutKnop, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 89, 90, 33));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/layoutCorendonFinalVeranderd.png"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Background, org.jdesktop.beansbinding.ELProperty.create("${background}"), Background, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButton1MouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(AdminHome);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_homeButton1MouseClicked

    private void homeButton1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButton1MouseEntered
        homeButton1.setBackground(new java.awt.Color(153,51,51));
    }//GEN-LAST:event_homeButton1MouseEntered

    private void homeButton1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButton1MouseExited
        homeButton1.setBackground(Color.white);
    }//GEN-LAST:event_homeButton1MouseExited

    private void editButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(adminPersonal);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_editButtonMouseClicked

    private void editButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseEntered
        editButton.setBackground(new java.awt.Color(153,51,51));
    }//GEN-LAST:event_editButtonMouseEntered

    private void editButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editButtonMouseExited
        editButton.setBackground(Color.white);
    }//GEN-LAST:event_editButtonMouseExited

    private void createButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(Create);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_createButtonMouseClicked

    private void createButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseEntered
        createButton.setBackground(new java.awt.Color(153,51,51));
    }//GEN-LAST:event_createButtonMouseEntered

    private void createButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_createButtonMouseExited
        createButton.setBackground(Color.white);
    }//GEN-LAST:event_createButtonMouseExited

    private void helpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(Help);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_helpButtonMouseClicked

    private void helpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseEntered
        helpButton.setBackground(new java.awt.Color(153,51,51));
    }//GEN-LAST:event_helpButtonMouseEntered

    private void helpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseExited
        helpButton.setBackground(Color.white);
    }//GEN-LAST:event_helpButtonMouseExited

    private void addressEditTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressEditTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressEditTextActionPerformed

    private void addressCreateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressCreateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressCreateTextActionPerformed

    private void accounttypeCreateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_accounttypeCreateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_accounttypeCreateTextActionPerformed

    private void addressDeleteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addressDeleteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_addressDeleteTextActionPerformed

    private void logoutKnopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseEntered
        logoutKnop.setBackground(new java.awt.Color(224, 90, 90));
    }//GEN-LAST:event_logoutKnopMouseEntered

    private void logoutKnopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseExited
        logoutKnop.setBackground(new java.awt.Color(153, 51, 51));
    }//GEN-LAST:event_logoutKnopMouseExited

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //open database connection
        dbm.openConnection();

        CreateAccount createaccount = new CreateAccount("",false, newusernameCreateText.getText(), newpasswordCreateText.getText(), accounttypeCreateText.getText(), nameCreateText.getText(), addressCreateText.getText(), cityCreateText.getText(), postalcodeCreateText.getText(), countryCreateText.getText(), emailCreateText.getText());
        if ("employee".equals(createaccount.accounttype)) {
            createaccount.accounttype = "employee";
        }
        if ("Employee".equals(createaccount.accounttype)) {
            createaccount.accounttype = "employee";
        }
        if ("Manager".equals(createaccount.accounttype)) {
            createaccount.accounttype = "manager";
        }
        if ("Admin".equals(createaccount.accounttype)) {
            createaccount.accounttype = "admin";
        }
        if ("Administrator".equals(createaccount.accounttype)) {
            createaccount.accounttype = "admin";
        }
        if ("administrator".equals(createaccount.accounttype)) {
            createaccount.accounttype = "admin";
        }
        qm.insertcreateaccount(createaccount);
        Employee.infoBox("Succesfully Saved\n" + "Username:  " + newusernameCreateText.getText(), "Saved");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void editPersonalinfoButtonKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_editPersonalinfoButtonKeyPressed

    }//GEN-LAST:event_editPersonalinfoButtonKeyPressed

    private void editPersonalinfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editPersonalinfoButtonActionPerformed
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(adminEdit);
        jPanel1.repaint();
        jPanel1.revalidate(); 
    }//GEN-LAST:event_editPersonalinfoButtonActionPerformed

    private void searchaccountPersonalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchaccountPersonalButtonActionPerformed
        Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //open database connection
        dbm.openConnection();

        if (searchPersonalText.getText().equals("")) 
            {
                udl = qm.getUsers("SELECT * from createaccount");
            }else
        {
          udl = qm.getUsers("SELECT * from createaccount where username  ='" + searchPersonalText.getText() + "'");
        }
            DefaultListModel<String> model = new DefaultListModel<String>();

            for (CreateAccount s : udl) {
                model.addElement(s.username);
                System.out.println(s.username);
          //  userId = Integer.parseInt(s.userid);
               
              
            }
            listUsers.setModel(model);

    }//GEN-LAST:event_searchaccountPersonalButtonActionPerformed

    private void usernamePersonalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_usernamePersonalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_usernamePersonalTextActionPerformed

    private void newusernameCreateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newusernameCreateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newusernameCreateTextActionPerformed

    private void deleteaccountPersonalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_deleteaccountPersonalButtonMouseClicked
      Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //open database connection
        dbm.openConnection();
     
    }//GEN-LAST:event_deleteaccountPersonalButtonMouseClicked

    private void deleteaccountPersonalButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteaccountPersonalButtonActionPerformed
         Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //open database connection
        dbm.openConnection();
        qm.deleteUser(userId);
    }//GEN-LAST:event_deleteaccountPersonalButtonActionPerformed

    private void editPersonalButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editPersonalButtonMouseClicked
         Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //open database connection
        dbm.openConnection(); 
        qm.updateUser(usernamePersonalText.getText(), passwordPersonalText.getText());
    }//GEN-LAST:event_editPersonalButtonMouseClicked

    private void passwordPersonalTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_passwordPersonalTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_passwordPersonalTextActionPerformed

    private void editAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editAdminButtonActionPerformed
        
    }//GEN-LAST:event_editAdminButtonActionPerformed

    private void saveEditActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_saveEditActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_saveEditActionPerformed

    private void repeatpasswordCreateTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_repeatpasswordCreateTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_repeatpasswordCreateTextActionPerformed

    private void logoutKnopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseClicked
  Login login = new Login();
        login.setVisible(true);
        this.dispose();     
    }//GEN-LAST:event_logoutKnopMouseClicked

    private void editAdminButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_editAdminButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(adminEdit);
        jPanel1.repaint();
        jPanel1.revalidate(); 
    }//GEN-LAST:event_editAdminButtonMouseClicked

    private void nameDeleteTextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameDeleteTextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameDeleteTextActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;

                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Admin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Admin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Admin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Admin.class
                    .getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Admin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AdminCreate;
    private javax.swing.JPanel AdminDelete;
    private javax.swing.JPanel AdminHelp;
    private javax.swing.JPanel AdminHome;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel BackgroundAdmin;
    private javax.swing.JPanel Create;
    private javax.swing.JPanel Delete;
    private javax.swing.JPanel Edit;
    private javax.swing.JPanel Help;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel ID;
    private javax.swing.JLabel Name;
    private javax.swing.JLabel accountinfoCreate;
    private javax.swing.JLabel accountinfoDelete;
    private javax.swing.JLabel accountinfoEdit;
    private javax.swing.JLabel accounttypeCreate;
    private javax.swing.JTextField accounttypeCreateText;
    private javax.swing.JComboBox accounttypeDropboxEdit;
    private javax.swing.JLabel accounttypePersonal;
    private javax.swing.JTextField accounttypePersonalText;
    private javax.swing.JLabel accountypeEdit;
    private javax.swing.JLabel addressAdmin;
    private javax.swing.JLabel addressAdminText;
    private javax.swing.JLabel addressCreate;
    private javax.swing.JTextField addressCreateText;
    private javax.swing.JLabel addressDelete;
    private javax.swing.JTextField addressDeleteText;
    private javax.swing.JLabel addressEdit;
    private javax.swing.JTextField addressEditText;
    private javax.swing.JPanel adminEdit;
    private javax.swing.JPanel adminPersonal;
    private javax.swing.JLabel areusureDelete;
    private javax.swing.JLabel backgroundCreate;
    private javax.swing.JLabel backgroundDelete;
    private javax.swing.JLabel backgroundEdit;
    private javax.swing.JLabel backgroundPersonal;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel chooseaccountDelete;
    private javax.swing.JLabel cityAdmin;
    private javax.swing.JLabel cityAdminText;
    private javax.swing.JLabel cityCreate;
    private javax.swing.JTextField cityCreateText;
    private javax.swing.JLabel cityDelete;
    private javax.swing.JTextField cityDeleteText;
    private javax.swing.JLabel cityEdit;
    private javax.swing.JTextField cityEditText;
    private javax.swing.JLabel corendonCreate;
    private javax.swing.JLabel corendonDelete;
    private javax.swing.JLabel corendonEdit;
    private javax.swing.JLabel corendonPersonal;
    private javax.swing.JLabel countryAdmin;
    private javax.swing.JLabel countryAdminText;
    private javax.swing.JLabel countryCreate;
    private javax.swing.JTextField countryCreateText;
    private javax.swing.JLabel countryDelete;
    private javax.swing.JTextField countryDeleteText;
    private javax.swing.JLabel countryEdit;
    private javax.swing.JTextField countryEditText;
    private javax.swing.JLabel createButton;
    private javax.swing.JLabel dateAdmin;
    private javax.swing.JLabel dateAdminText;
    private javax.swing.JLabel dateofbirthCreate;
    private javax.swing.JButton deleteDeleteButton;
    private javax.swing.JButton deleteaccountPersonalButton;
    private javax.swing.JToggleButton editAdminButton;
    private javax.swing.JLabel editButton;
    private javax.swing.JButton editPersonalButton;
    private javax.swing.JButton editPersonalinfoButton;
    private javax.swing.JLabel editinfoPersonal;
    private javax.swing.JLabel emailAdmin;
    private javax.swing.JLabel emailAdminText;
    private javax.swing.JLabel emailCreate;
    private javax.swing.JTextField emailCreateText;
    private javax.swing.JLabel emailDelete;
    private javax.swing.JTextField emailDeleteText;
    private javax.swing.JLabel emailEdit;
    private javax.swing.JTextField emailEditText;
    private javax.swing.JLabel helpButton;
    private javax.swing.JLabel homeButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JPanel jPanel1;
    public javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JList listUsers;
    private javax.swing.JLabel logoutKnop;
    private javax.swing.JPanel menu1;
    private javax.swing.JLabel nameAdmin;
    private javax.swing.JLabel nameAdminText;
    private javax.swing.JLabel nameCreate;
    private javax.swing.JTextField nameCreateText;
    private javax.swing.JLabel nameDelete;
    private javax.swing.JTextField nameDeleteText;
    private javax.swing.JLabel nameEdit;
    private javax.swing.JTextField nameEditText;
    private javax.swing.JLabel newpasswordCreate;
    private javax.swing.JPasswordField newpasswordCreateText;
    private javax.swing.JLabel newpasswordEdit;
    private javax.swing.JTextField newpasswordEditText;
    private javax.swing.JLabel newusernameCreate;
    private javax.swing.JTextField newusernameCreateText;
    private javax.swing.JLabel newusernameEdit;
    private javax.swing.JTextField newusernameEditText;
    private javax.swing.JLabel oldpasswordEdit;
    private javax.swing.JTextField oldpasswordEditText;
    private javax.swing.JLabel passwordPersonal;
    private javax.swing.JTextField passwordPersonalText;
    private javax.swing.JLabel personalInfoEdit;
    private javax.swing.JLabel personalinfoCreate;
    private javax.swing.JLabel personalinfoDelete;
    private javax.swing.JLabel postalcodeAdmin;
    private javax.swing.JLabel postalcodeAdminText;
    private javax.swing.JLabel postalcodeCreate;
    private javax.swing.JTextField postalcodeCreateText;
    private javax.swing.JLabel postalcodeDelete;
    private javax.swing.JTextField postalcodeDeleteText;
    private javax.swing.JLabel postalcodeEdit;
    private javax.swing.JTextField postalcodeEditText;
    private javax.swing.JLabel profileAdmin;
    private javax.swing.JLabel repeatpasswordCreate;
    private javax.swing.JPasswordField repeatpasswordCreateText;
    private javax.swing.JLabel repeatpasswordEdit;
    private javax.swing.JTextField repeatpasswordEditText;
    private javax.swing.JButton saveEdit;
    private javax.swing.JTextField searchPersonalText;
    private javax.swing.JButton searchaccountPersonalButton;
    private javax.swing.JButton selectaccountPersonalButton;
    private javax.swing.JLabel usernameAdmin;
    private javax.swing.JLabel usernameAdminText;
    private javax.swing.JLabel usernamePersonal;
    private javax.swing.JTextField usernamePersonalText;
    private javax.swing.JLabel welcomeAdmin;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    double width = screenSize.getWidth();
    double height = screenSize.getHeight();
}
