package view;

import Connectivity.Dbmanager;
import Connectivity.QueryManager;
import java.awt.BorderLayout;
import java.awt.Button;
import java.awt.CardLayout;
import java.awt.Color;
import java.awt.Container;
import java.awt.Dimension;
import java.awt.FlowLayout;
import java.awt.PopupMenu;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import model.Baggage;
import model.CreateAccount;
import model.Customerinfo;
import view.Login;
import org.netbeans.lib.awtextra.AbsoluteLayout;



/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author EdoTyran
 */
public class Employee extends javax.swing.JFrame {
     ArrayList<Customerinfo> lldd = new ArrayList();

public static void infoBox(String infoMessage, String titleBar)
   
{
        JOptionPane.showMessageDialog(null, infoMessage, "Notification: " + titleBar, JOptionPane.INFORMATION_MESSAGE);
    }
 
//public void getCustomer (String id){
//        CreateAccount customerInfo = new CreateAccount("",false,"", "", "", "", "", "", "", "", "");
//        Dbmanager dbm = new Dbmanager();   
//        QueryManager qm = new QueryManager(dbm);
//            //open database connection
//            dbm.openConnection();
//          CreateAccount cm;  
//        cm = qm.getCustomer(id);    
//       firstname.setText(cm.name);
//        customerInfo.firstName = txtFirstName.getText();
//        customerInfo.lastName = txtLastName.getText();
//        customerInfo.sex = 1;
//        customerInfo.addressHome = txtAddressHome.getText();
//        customerInfo.cityHome = txtCityHome.getText();
//        customerInfo.stateHome = txtStateHome.getText();
//        customerInfo.countryHome = txtCountryHome.getText();
//        customerInfo.zipHome = txtZipHome.getText();
//        customerInfo.addressHol = txtAddressHol.getText();
//        customerInfo.cityHol = txtCityHol.getText();
//        customerInfo.stateHol = txtStateHol.getText();
//        customerInfo.countryHol = txtCountryHol.getText();
//        customerInfo.zipHol = txtZipHol.getText();
//        customerInfo.phoneNumber = txtPhone.getText();
//        customerInfo.homeHol = 1;
//        customerInfo.labelNumber= txtLuggageLabel.getText();

   
                              
  public void SetUser(CreateAccount createaccount) {
        LoggedIN.setText("Logged in as: " +createaccount.accounttype);
        jLabel54.setText(createaccount.username);
        welcomeText.setText("Welcome " + createaccount.username+ "," );
        jLabel46.setText("Not Set");
        jLabel47.setText("Not Set");
        jLabel48.setText("Not Set");
        jLabel49.setText("Not Set");
        jLabel51.setText("Not Set");
        jLabel52.setText("Not Set");
        jLabel53.setText("Not Set");
        

        if ("employee".equals(createaccount.accounttype)) {
            setVisible(true);
        } else {
            setVisible(false);
        }
    }
    public ArrayList<Baggage> lld = new ArrayList();
public JTable table;
public JFrame frame = new JFrame();

int xMouse, yMouse;
private PopupMenu Tabel;

    /**
     * Creates new form Employee
     */
    public Employee() {
       
        super("Lost Baggage");
        setSize(1300,650);
        setResizable(false);
        setDefaultCloseOperation(EXIT_ON_CLOSE);
        
        initComponents();
        frame.setLocationRelativeTo( null );
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(EmployeeHome);
        
       
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        bindingGroup = new org.jdesktop.beansbinding.BindingGroup();

        LoggedIN = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        EmployeeHome = new javax.swing.JPanel();
        welcomeText = new javax.swing.JLabel();
        IDText = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel40 = new javax.swing.JLabel();
        jLabel41 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jLabel46 = new javax.swing.JLabel();
        jLabel47 = new javax.swing.JLabel();
        jLabel48 = new javax.swing.JLabel();
        jLabel49 = new javax.swing.JLabel();
        jLabel51 = new javax.swing.JLabel();
        jLabel52 = new javax.swing.JLabel();
        jLabel53 = new javax.swing.JLabel();
        jLabel54 = new javax.swing.JLabel();
        Backgroundlabel = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        Search = new javax.swing.JPanel();
        EmployeeSearch = new javax.swing.JPanel();
        SearchBaggage = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        SearchBaggage3 = new javax.swing.JTextField();
        jLabel50 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jButton5 = new javax.swing.JButton();
        AddBaggage = new javax.swing.JPanel();
        EmpolyeeAddBaggage = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        description = new javax.swing.JTextField();
        collor = new javax.swing.JTextField();
        brand = new javax.swing.JTextField();
        weight = new javax.swing.JTextField();
        materials = new javax.swing.JTextField();
        BaggageID = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel29 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        email = new javax.swing.JTextField();
        addressEdit = new javax.swing.JLabel();
        zipEdit = new javax.swing.JLabel();
        emailEdit = new javax.swing.JLabel();
        postal = new javax.swing.JTextField();
        name = new javax.swing.JTextField();
        countryEdit = new javax.swing.JLabel();
        cityEdit = new javax.swing.JLabel();
        shippingAdress = new javax.swing.JTextField();
        city = new javax.swing.JTextField();
        nameEdit = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        adress = new javax.swing.JTextField();
        addressEdit1 = new javax.swing.JLabel();
        country = new javax.swing.JTextField();
        jButton3 = new javax.swing.JButton();
        Department1 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        Help = new javax.swing.JPanel();
        EmployeeHelp = new javax.swing.JPanel();
        jLabel15 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jFileChooser1 = new javax.swing.JFileChooser();
        jLabel5 = new javax.swing.JLabel();
        SubmitBaggage = new javax.swing.JPanel();
        EmployeeSumbitBaggage = new javax.swing.JPanel();
        materials1 = new javax.swing.JTextField();
        weight1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        jLabel21 = new javax.swing.JLabel();
        brand1 = new javax.swing.JTextField();
        color1 = new javax.swing.JTextField();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        department1 = new javax.swing.JTextField();
        Baggageid1 = new javax.swing.JTextField();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel26 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        description1 = new javax.swing.JTextPane();
        jLabel33 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Manage = new javax.swing.JPanel();
        ManageBaggagePanel = new javax.swing.JPanel();
        SearchBaggage1 = new javax.swing.JTextField();
        jLabel42 = new javax.swing.JLabel();
        jLabel43 = new javax.swing.JLabel();
        jLabel44 = new javax.swing.JLabel();
        jLabel45 = new javax.swing.JLabel();
        menu = new javax.swing.JPanel();
        homeButton = new javax.swing.JLabel();
        searchButton = new javax.swing.JLabel();
        addBaggageButton = new javax.swing.JLabel();
        submitBaggageButton = new javax.swing.JLabel();
        helpButton = new javax.swing.JLabel();
        ManageBaggagee = new javax.swing.JLabel();
        logoutKnop = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Lost Baggage");
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        LoggedIN.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        getContentPane().add(LoggedIN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 80, 290, 50));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        jPanel1.setLayout(new java.awt.CardLayout());

        Home.setBackground(new java.awt.Color(255, 255, 255));
        Home.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Home.setLayout(new java.awt.BorderLayout());

        EmployeeHome.setBackground(new java.awt.Color(153, 51, 51));
        EmployeeHome.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 5));
        EmployeeHome.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        welcomeText.setFont(new java.awt.Font("Tahoma", 2, 30)); // NOI18N
        welcomeText.setText("Welcome,");
        EmployeeHome.add(welcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 180, 50));

        IDText.setText("Username:");
        EmployeeHome.add(IDText, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 240, 90, 20));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        EmployeeHome.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        jLabel37.setText("Email     :");
        EmployeeHome.add(jLabel37, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 290, -1, -1));

        jLabel35.setText("Country    :");
        EmployeeHome.add(jLabel35, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 260, 70, 20));

        jLabel36.setText("Zip/Postal code   :");
        EmployeeHome.add(jLabel36, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 230, 90, 20));

        jLabel38.setText("City     :");
        EmployeeHome.add(jLabel38, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 200, 50, 20));

        jLabel39.setText("Date :");
        EmployeeHome.add(jLabel39, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 300, 60, 20));

        jLabel40.setText("Name   :");
        EmployeeHome.add(jLabel40, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 210, -1, 20));

        jLabel41.setText("Address   :");
        EmployeeHome.add(jLabel41, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 270, 60, 20));

        jLabel14.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel14.setText("Profile :");
        EmployeeHome.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 150, 90, 40));

        jToggleButton1.setText("Edit");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        EmployeeHome.add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 340, -1, -1));

        jLabel46.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel46.setText("jLabel46");
        EmployeeHome.add(jLabel46, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 90, 20));

        jLabel47.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel47.setText("jLabel46");
        EmployeeHome.add(jLabel47, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 270, 90, 20));

        jLabel48.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel48.setText("jLabel46");
        EmployeeHome.add(jLabel48, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 300, 90, 20));

        jLabel49.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel49.setText("jLabel46");
        EmployeeHome.add(jLabel49, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 90, 20));

        jLabel51.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel51.setText("jLabel46");
        EmployeeHome.add(jLabel51, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 230, 90, 20));

        jLabel52.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel52.setText("jLabel46");
        EmployeeHome.add(jLabel52, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 260, 90, 20));

        jLabel53.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel53.setText("jLabel46");
        EmployeeHome.add(jLabel53, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 290, 90, 20));

        jLabel54.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel54.setText("jLabel46");
        EmployeeHome.add(jLabel54, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 210, 90, 20));

        Backgroundlabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        Backgroundlabel.setToolTipText("");
        Backgroundlabel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        EmployeeHome.add(Backgroundlabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 880, 430));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/5Pli3Pfm3V.jpg"))); // NOI18N
        EmployeeHome.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 20, 500, 80));

        Home.add(EmployeeHome, java.awt.BorderLayout.CENTER);

        jPanel1.add(Home, "card2");

        Search.setBackground(new java.awt.Color(255, 255, 255));
        Search.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Search.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeSearch.setBackground(new java.awt.Color(255, 255, 255));
        EmployeeSearch.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        EmployeeSearch.setForeground(new java.awt.Color(255, 255, 255));
        EmployeeSearch.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchBaggage.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        SearchBaggage.setText("Search BaggageID");
        EmployeeSearch.add(SearchBaggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 210, 540, -1));

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seoLogo.png"))); // NOI18N
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });
        EmployeeSearch.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 200, -1, -1));

        jLabel11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel11.setText("jLabel11");
        EmployeeSearch.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        EmployeeSearch.add(jLabel27, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        SearchBaggage3.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        SearchBaggage3.setText("Search customer");
        EmployeeSearch.add(SearchBaggage3, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 540, -1));

        jLabel50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seoLogo.png"))); // NOI18N
        jLabel50.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel50MouseClicked(evt);
            }
        });
        EmployeeSearch.add(jLabel50, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        jButton4.setText("View all");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        EmployeeSearch.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 120, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel3.setToolTipText("");
        jLabel3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        EmployeeSearch.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 971, 482));
        EmployeeSearch.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 250, 90, 90));

        jButton5.setText("View all bagaggel");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        EmployeeSearch.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 330, 120, -1));

        Search.add(EmployeeSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 500));

        jPanel1.add(Search, "card3");

        AddBaggage.setBackground(new java.awt.Color(255, 255, 255));
        AddBaggage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        AddBaggage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmpolyeeAddBaggage.setBackground(new java.awt.Color(153, 51, 51));
        EmpolyeeAddBaggage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, java.awt.Color.lightGray));
        EmpolyeeAddBaggage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel13.setText("jLabel11");
        EmpolyeeAddBaggage.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel1.setText("Department :");
        EmpolyeeAddBaggage.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 200, -1, 20));

        jLabel2.setText("Color :");
        EmpolyeeAddBaggage.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 230, 40, 20));

        jLabel6.setText("Brand :");
        EmpolyeeAddBaggage.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 280, 50, 40));

        jLabel8.setText("Description :");
        EmpolyeeAddBaggage.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, -1, -1));

        jLabel16.setText("Materials :");
        EmpolyeeAddBaggage.add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 320, -1, 20));

        jLabel17.setText("   BaggageId :");
        EmpolyeeAddBaggage.add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 170, 80, 30));

        jLabel18.setText("Weight :");
        EmpolyeeAddBaggage.add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 260, -1, 20));

        description.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        description.setText("Example: yellow");
        description.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                descriptionActionPerformed(evt);
            }
        });
        EmpolyeeAddBaggage.add(description, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 230, 120, -1));

        collor.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        collor.setText("Example: Black");
        collor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                collorActionPerformed(evt);
            }
        });
        EmpolyeeAddBaggage.add(collor, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 260, 120, -1));

        brand.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        brand.setText("Example: Gucci");
        brand.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandActionPerformed(evt);
            }
        });
        EmpolyeeAddBaggage.add(brand, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 290, 120, -1));

        weight.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        weight.setText("Example: 32KG");
        weight.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weightActionPerformed(evt);
            }
        });
        EmpolyeeAddBaggage.add(weight, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 160, 110, 210));

        materials.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        materials.setText("Example: leather");
        materials.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materialsActionPerformed(evt);
            }
        });
        EmpolyeeAddBaggage.add(materials, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 120, -1));

        BaggageID.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        BaggageID.setText("Example: 3283852");
        BaggageID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BaggageIDActionPerformed(evt);
            }
        });
        EmpolyeeAddBaggage.add(BaggageID, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 120, -1));

        jButton1.setText("Save & Exit");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        EmpolyeeAddBaggage.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, -1, -1));

        jLabel29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        EmpolyeeAddBaggage.add(jLabel29, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 360, 160, 50));

        jLabel31.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel31.setText("Personal information");
        EmpolyeeAddBaggage.add(jLabel31, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 100, 250, -1));

        email.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        email.setText("Example: John@corendon.com");
        EmpolyeeAddBaggage.add(email, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 330, 240, -1));

        addressEdit.setText("Ship address   :");
        EmpolyeeAddBaggage.add(addressEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 210, 80, 20));

        zipEdit.setText("Zip/Postal code   :");
        EmpolyeeAddBaggage.add(zipEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 90, 20));

        emailEdit.setText("Email     :");
        EmpolyeeAddBaggage.add(emailEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 330, -1, 30));

        postal.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        postal.setText("Example: 1055GK");
        EmpolyeeAddBaggage.add(postal, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 240, -1));

        name.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        name.setText("example: john");
        name.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nameActionPerformed(evt);
            }
        });
        EmpolyeeAddBaggage.add(name, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 240, -1));

        countryEdit.setText("Country    :");
        EmpolyeeAddBaggage.add(countryEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 300, 70, 20));

        cityEdit.setText("City     :");
        EmpolyeeAddBaggage.add(cityEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 240, 50, 30));

        shippingAdress.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        shippingAdress.setText("Example: Egidiusstraat");
        shippingAdress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                shippingAdressActionPerformed(evt);
            }
        });
        EmpolyeeAddBaggage.add(shippingAdress, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 240, -1));

        city.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        city.setText("Example: Amsterdam");
        EmpolyeeAddBaggage.add(city, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 240, 240, -1));

        nameEdit.setText("Name   :");
        EmpolyeeAddBaggage.add(nameEdit, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 150, -1, 20));

        jLabel32.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel32.setText("Baggage information");
        EmpolyeeAddBaggage.add(jLabel32, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 110, 250, -1));

        adress.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        adress.setText("Example: Egidiusstraat");
        adress.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                adressActionPerformed(evt);
            }
        });
        EmpolyeeAddBaggage.add(adress, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 180, 240, -1));

        addressEdit1.setText("Address   :");
        EmpolyeeAddBaggage.add(addressEdit1, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 180, 60, 20));

        country.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        country.setText("Example: The Netherlands");
        EmpolyeeAddBaggage.add(country, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 240, -1));

        jButton3.setText("Save & Exit");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        EmpolyeeAddBaggage.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 390, -1, -1));

        Department1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        Department1.setText("Example: Home");
        Department1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Department1ActionPerformed(evt);
            }
        });
        EmpolyeeAddBaggage.add(Department1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 200, 120, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel4.setToolTipText("");
        jLabel4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        EmpolyeeAddBaggage.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 900, 490));

        AddBaggage.add(EmpolyeeAddBaggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        jPanel1.add(AddBaggage, "card4");

        Help.setBackground(new java.awt.Color(255, 255, 255));
        Help.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Help.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeHelp.setBackground(new java.awt.Color(153, 51, 51));
        EmployeeHelp.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, java.awt.Color.lightGray));
        EmployeeHelp.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel15.setText("jLabel11");
        EmployeeHelp.add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        EmployeeHelp.add(jLabel30, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        jLabel34.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel34.setText("Download PDF: ");
        EmployeeHelp.add(jLabel34, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 180, -1, -1));
        EmployeeHelp.add(jFileChooser1, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 110, -1, 270));

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel5.setToolTipText("");
        jLabel5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        EmployeeHelp.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 971, 482));

        Help.add(EmployeeHelp, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 490));

        jPanel1.add(Help, "card5");

        SubmitBaggage.setBackground(new java.awt.Color(255, 255, 255));
        SubmitBaggage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        SubmitBaggage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        EmployeeSumbitBaggage.setBackground(new java.awt.Color(153, 51, 51));
        EmployeeSumbitBaggage.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED, null, java.awt.Color.gray, null, java.awt.Color.lightGray));
        EmployeeSumbitBaggage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        materials1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        materials1.setText("Example: Leather");
        materials1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                materials1ActionPerformed(evt);
            }
        });
        EmployeeSumbitBaggage.add(materials1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 360, 120, -1));

        weight1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        weight1.setText("Example: 34KG");
        weight1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                weight1ActionPerformed(evt);
            }
        });
        EmployeeSumbitBaggage.add(weight1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 330, 120, -1));

        jLabel19.setText("Materials :");
        EmployeeSumbitBaggage.add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 360, -1, 20));

        jLabel20.setText("Weight :");
        EmployeeSumbitBaggage.add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 330, -1, 20));

        jLabel21.setText("Brand :");
        EmployeeSumbitBaggage.add(jLabel21, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 300, -1, -1));

        brand1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        brand1.setText("Example: Gucci");
        brand1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brand1ActionPerformed(evt);
            }
        });
        EmployeeSumbitBaggage.add(brand1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 300, 120, -1));

        color1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        color1.setText("Example: Yellow");
        color1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                color1ActionPerformed(evt);
            }
        });
        EmployeeSumbitBaggage.add(color1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 270, 120, -1));

        jLabel22.setText("Color :");
        EmployeeSumbitBaggage.add(jLabel22, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 270, 40, -1));

        jLabel23.setText("Department :");
        EmployeeSumbitBaggage.add(jLabel23, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 240, -1, -1));

        department1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        department1.setText("Example: Home");
        department1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                department1ActionPerformed(evt);
            }
        });
        EmployeeSumbitBaggage.add(department1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 240, 120, -1));

        Baggageid1.setFont(new java.awt.Font("Tahoma", 2, 11)); // NOI18N
        Baggageid1.setText("Example: 141453");
        Baggageid1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Baggageid1ActionPerformed(evt);
            }
        });
        EmployeeSumbitBaggage.add(Baggageid1, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 210, 120, -1));

        jLabel24.setText("Flight number :");
        EmployeeSumbitBaggage.add(jLabel24, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 210, -1, -1));

        jLabel25.setText("Description :");
        EmployeeSumbitBaggage.add(jLabel25, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 210, -1, -1));

        jButton2.setText("Save & Exit");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        EmployeeSumbitBaggage.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 400, -1, -1));

        jLabel26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel26.setText("jLabel11");
        EmployeeSumbitBaggage.add(jLabel26, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        EmployeeSumbitBaggage.add(jLabel28, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        jScrollPane5.setViewportView(description1);

        EmployeeSumbitBaggage.add(jScrollPane5, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 210, 260, 120));

        jLabel33.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel33.setText("Baggage information");
        EmployeeSumbitBaggage.add(jLabel33, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 120, 250, -1));

        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel7.setToolTipText("");
        jLabel7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        EmployeeSumbitBaggage.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 940, 482));

        SubmitBaggage.add(EmployeeSumbitBaggage, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 490));

        jPanel1.add(SubmitBaggage, "card6");

        Manage.setBackground(new java.awt.Color(255, 255, 255));
        Manage.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 9));
        Manage.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        ManageBaggagePanel.setBackground(new java.awt.Color(255, 255, 255));
        ManageBaggagePanel.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 5, true));
        ManageBaggagePanel.setForeground(new java.awt.Color(255, 255, 255));
        ManageBaggagePanel.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        SearchBaggage1.setText("baggageID");
        ManageBaggagePanel.add(SearchBaggage1, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 540, -1));

        jLabel42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/seoLogo.png"))); // NOI18N
        jLabel42.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel42MouseClicked(evt);
            }
        });
        ManageBaggagePanel.add(jLabel42, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 120, -1, -1));

        jLabel43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/corendon-airlines.jpg"))); // NOI18N
        jLabel43.setText("jLabel11");
        ManageBaggagePanel.add(jLabel43, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 30, 300, 70));

        jLabel44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Vliegtuig_CorendonNL-2-stijgend.png"))); // NOI18N
        ManageBaggagePanel.add(jLabel44, new org.netbeans.lib.awtextra.AbsoluteConstraints(710, 370, 160, 50));

        jLabel45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/00000001.JPG"))); // NOI18N
        jLabel45.setToolTipText("");
        jLabel45.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true));
        ManageBaggagePanel.add(jLabel45, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 971, 482));

        Manage.add(ManageBaggagePanel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 980, 500));

        jPanel1.add(Manage, "card7");

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 910, 460));

        menu.setBackground(new java.awt.Color(255, 255, 255));

        homeButton.setBackground(new java.awt.Color(255, 255, 255));
        homeButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        homeButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        homeButton.setText("Home");
        homeButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        homeButton.setOpaque(true);
        homeButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homeButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homeButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homeButtonMouseExited(evt);
            }
        });

        searchButton.setBackground(new java.awt.Color(255, 255, 255));
        searchButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        searchButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        searchButton.setText("Search");
        searchButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        searchButton.setOpaque(true);
        searchButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                searchButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                searchButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                searchButtonMouseExited(evt);
            }
        });

        addBaggageButton.setBackground(new java.awt.Color(255, 255, 255));
        addBaggageButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        addBaggageButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addBaggageButton.setText("Add baggage");
        addBaggageButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        addBaggageButton.setOpaque(true);
        addBaggageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addBaggageButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                addBaggageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                addBaggageButtonMouseExited(evt);
            }
        });

        submitBaggageButton.setBackground(new java.awt.Color(255, 255, 255));
        submitBaggageButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        submitBaggageButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        submitBaggageButton.setText("Found Baggage");
        submitBaggageButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        submitBaggageButton.setOpaque(true);
        submitBaggageButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                submitBaggageButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                submitBaggageButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                submitBaggageButtonMouseExited(evt);
            }
        });

        helpButton.setBackground(new java.awt.Color(255, 255, 255));
        helpButton.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        helpButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        helpButton.setText("Help");
        helpButton.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        helpButton.setOpaque(true);
        helpButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                helpButtonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                helpButtonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                helpButtonMouseExited(evt);
            }
        });

        ManageBaggagee.setBackground(new java.awt.Color(255, 255, 255));
        ManageBaggagee.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        ManageBaggagee.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ManageBaggagee.setText("Manage Baggage");
        ManageBaggagee.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ManageBaggagee.setOpaque(true);
        ManageBaggagee.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ManageBaggageeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                ManageBaggageeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ManageBaggageeMouseExited(evt);
            }
        });

        javax.swing.GroupLayout menuLayout = new javax.swing.GroupLayout(menu);
        menu.setLayout(menuLayout);
        menuLayout.setHorizontalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(homeButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 178, Short.MAX_VALUE)
            .addComponent(addBaggageButton, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(submitBaggageButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(helpButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(ManageBaggagee, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        menuLayout.setVerticalGroup(
            menuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(menuLayout.createSequentialGroup()
                .addComponent(homeButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addComponent(searchButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addBaggageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ManageBaggagee, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(submitBaggageButton, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(helpButton, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 69, Short.MAX_VALUE))
        );

        getContentPane().add(menu, new org.netbeans.lib.awtextra.AbsoluteConstraints(22, 180, 178, 410));

        logoutKnop.setBackground(new java.awt.Color(147, 51, 51));
        logoutKnop.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        logoutKnop.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        logoutKnop.setText("LOGOUT");
        logoutKnop.setOpaque(true);
        logoutKnop.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutKnopMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutKnopMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutKnopMouseExited(evt);
            }
        });
        getContentPane().add(logoutKnop, new org.netbeans.lib.awtextra.AbsoluteConstraints(1210, 89, 90, 33));

        Background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/layoutCorendonFinalVeranderd.png"))); // NOI18N

        org.jdesktop.beansbinding.Binding binding = org.jdesktop.beansbinding.Bindings.createAutoBinding(org.jdesktop.beansbinding.AutoBinding.UpdateStrategy.READ_WRITE, Background, org.jdesktop.beansbinding.ELProperty.create("${background}"), Background, org.jdesktop.beansbinding.BeanProperty.create("background"));
        bindingGroup.addBinding(binding);

        getContentPane().add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 650));

        bindingGroup.bind();

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void homeButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseEntered
        homeButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_homeButtonMouseEntered

    private void homeButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseExited
        homeButton.setBackground(Color.white);
    }//GEN-LAST:event_homeButtonMouseExited

    private void searchButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseEntered
        searchButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_searchButtonMouseEntered

    private void addBaggageButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBaggageButtonMouseEntered
        addBaggageButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_addBaggageButtonMouseEntered

    private void submitBaggageButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBaggageButtonMouseEntered
        submitBaggageButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_submitBaggageButtonMouseEntered

    private void helpButtonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseEntered
        helpButton.setBackground(Color.lightGray);
    }//GEN-LAST:event_helpButtonMouseEntered

    private void searchButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseExited
        searchButton.setBackground(Color.white);
    }//GEN-LAST:event_searchButtonMouseExited

    private void addBaggageButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBaggageButtonMouseExited
        addBaggageButton.setBackground(Color.white);
    }//GEN-LAST:event_addBaggageButtonMouseExited

    private void submitBaggageButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBaggageButtonMouseExited
        submitBaggageButton.setBackground(Color.white);
    }//GEN-LAST:event_submitBaggageButtonMouseExited

    private void helpButtonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseExited
        helpButton.setBackground(Color.white);
    }//GEN-LAST:event_helpButtonMouseExited

    private void homeButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homeButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(EmployeeHome);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_homeButtonMouseClicked

    private void searchButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_searchButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(EmployeeSearch);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_searchButtonMouseClicked

    private void addBaggageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addBaggageButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(AddBaggage);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_addBaggageButtonMouseClicked

    private void submitBaggageButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_submitBaggageButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(SubmitBaggage);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_submitBaggageButtonMouseClicked

    private void helpButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_helpButtonMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(Help);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_helpButtonMouseClicked

    private void logoutKnopMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseEntered
        logoutKnop.setBackground(new java.awt.Color(224,90,90));
    }//GEN-LAST:event_logoutKnopMouseEntered

    private void logoutKnopMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseExited
        logoutKnop.setBackground(new java.awt.Color(153,51,51));
    }//GEN-LAST:event_logoutKnopMouseExited

    private void descriptionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_descriptionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_descriptionActionPerformed

    private void collorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_collorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_collorActionPerformed

    private void brandActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brandActionPerformed

    private void weightActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weightActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weightActionPerformed

    private void materialsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materialsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materialsActionPerformed

    private void BaggageIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BaggageIDActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BaggageIDActionPerformed

    private void materials1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_materials1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_materials1ActionPerformed

    private void weight1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_weight1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_weight1ActionPerformed

    private void brand1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brand1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_brand1ActionPerformed

    private void color1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_color1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_color1ActionPerformed

    private void department1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_department1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_department1ActionPerformed

    private void Baggageid1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Baggageid1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Baggageid1ActionPerformed

    private void shippingAdressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_shippingAdressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_shippingAdressActionPerformed

    private void adressActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_adressActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_adressActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       Dbmanager dbm = new Dbmanager();
            QueryManager qm = new QueryManager(dbm);
            //open database connection
            dbm.openConnection();
           
            Baggage baggage = new Baggage(BaggageID.getText(),description.getText() ,collor.getText(),brand.getText(), weight.getText(),materials.getText(),description.getText()," ");
            qm.insertBaggage(baggage);
            Employee.infoBox("Succesfully Saved", "Saved");
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Dbmanager dbm = new Dbmanager();   
        QueryManager qm = new QueryManager(dbm);
            //open database connection
            dbm.openConnection();
           
            Baggage baggage = new Baggage(Baggageid1.getText(),department1.getText() ,color1.getText(),brand1.getText(), weight1.getText(),materials1.getText(),description1.getText()," ");
            qm.insertBaggage(baggage);
        Employee.infoBox("Succesfully Saved", "Saved");
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       Dbmanager dbm = new Dbmanager();
            QueryManager qm = new QueryManager(dbm);
            //open database connection
            dbm.openConnection();
           
            Customerinfo customerinfo = new Customerinfo (name.getText(),adress.getText(),shippingAdress.getText() ,city.getText(),postal.getText(),country.getText(),email.getText());
            qm.insertcutomerinfo(customerinfo);
            Employee.infoBox("Succesfully Saved", "Saved");
    }//GEN-LAST:event_jButton3ActionPerformed
    private void nameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nameActionPerformed
           

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
         Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //Open database connection

        dbm.openConnection();

        if (SearchBaggage.getText().equals(""))
        {
            lld = qm.getBaggage("SELECT * from baggage");
        } else
        {
            lld = qm.getBaggage("SELECT * FROM baggage WHERE baggageId = " + SearchBaggage.getText());
        }

        DefaultTableModel model = new DefaultTableModel();
        table = new JTable(model);

        // Create a couple of columns 
        model.addColumn("Baggageid");
        model.addColumn("color");
        model.addColumn("weight");
        model.addColumn("department");
        model.addColumn("material");
        model.addColumn("status");
        
        // Append a row 

        for (Baggage ld : lld)
        {
            model.addRow(new Object[]
            {
                ld.baggageId, ld.collor, ld.weight, ld.department, ld.materials,ld.status
            });
        }
        Container contentPane = this.getContentPane();
         contentPane.setLayout(new BorderLayout());
         contentPane.setSize(700, 500);
         contentPane.setBounds(200, 20, 700, 500);
         table.setSize(300, 150);
         JScrollPane jScrollPane1 = new JScrollPane(table);
         jScrollPane1.setSize(700, 500); 
         Button a=new Button("HI");
        jPanel1.removeAll();
        jPanel1.revalidate();   
        jPanel1.add(jScrollPane1);
        jPanel1.repaint();
        jPanel1.revalidate();

      
        jScrollPane1 = new JScrollPane(table);
        frame.add(jScrollPane1, BorderLayout.CENTER);
        frame.setSize(700, 500);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        jPanel1.removeAll();
        jPanel1.revalidate();   
        jPanel1.add(EmployeeSearch);
        jPanel1.repaint();
        jPanel1.revalidate();
       
       
            
       
        
     
        
    }//GEN-LAST:event_jLabel9MouseClicked

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
     Employee.infoBox("No Permission, \nContact Administrator: \nRichard ", "Error");
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void ManageBaggageeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageBaggageeMouseClicked
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(ManageBaggagePanel);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_ManageBaggageeMouseClicked

    private void ManageBaggageeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageBaggageeMouseEntered
      ManageBaggagee.setBackground(Color.lightGray);
    }//GEN-LAST:event_ManageBaggageeMouseEntered

    private void ManageBaggageeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ManageBaggageeMouseExited
       ManageBaggagee.setBackground(Color.white);
    }//GEN-LAST:event_ManageBaggageeMouseExited

    private void jLabel42MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel42MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jLabel42MouseClicked

    private void jLabel50MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel50MouseClicked
      Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //Open database connection
        dbm.openConnection();
        Customerinfo cm = new Customerinfo("", "", "", "", "", "", "");
       
         //AANROEPEN qm.something
        frame = new JFrame();

        DefaultTableModel model = new DefaultTableModel();
        table = new JTable(model);

        // Create a couple of columns 
        model.addColumn("Customer Name");
        model.addColumn("Adress");
        model.addColumn("Shipping Adress");
        model.addColumn("City");
        model.addColumn("Postal");
        model.addColumn("Country");
        model.addColumn("Email");
      
       
        // Append a row 
        
        if ( jLabel5.getText().equals(""))
        {
            lldd = qm.getCustomersinfoo("SELECT * from customerinfo");
        } else
        {
            lldd = qm.getCustomersinfoo("SELECT * FROM customerinfo WHERE CustomerName  = '" +   SearchBaggage3.getText() + "'"
                    + "OR City ='" +   SearchBaggage3.getText() + "';" );
        }

        for (Customerinfo cmm : lldd) {
            model.addRow(new Object[]{
               cmm.Name, cmm.Adress, cmm.shippingAdress, cmm.City, cmm.Postal, cmm.Country, cmm.Email });
          
        }

        jScrollPane1 = new JScrollPane(table);
        frame.add(jScrollPane1, BorderLayout.CENTER);
        frame.setSize(1500, 200);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        jPanel1.removeAll();
        jPanel1.revalidate();   
        jPanel1.add(EmployeeSearch);
        jPanel1.repaint();
        jPanel1.revalidate();
       
    }//GEN-LAST:event_jLabel50MouseClicked

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        Dbmanager dbm = new Dbmanager();
        QueryManager qm = new QueryManager(dbm);
        //Open database connection

        dbm.openConnection();

        if (SearchBaggage3.getText().equals("Search customer")) {
            lld = qm.getBaggage("SELECT * from baggage");
        } else if (SearchBaggage3.getText().equals("")){
            lld = qm.getBaggage("SELECT * FROM baggage");
        }

        DefaultTableModel model = new DefaultTableModel();
        table = new JTable(model);

        // Create a couple of columns
        model.addColumn("Baggageid");
        model.addColumn("color");
        model.addColumn("weight");
        model.addColumn("department");
        model.addColumn("material");
        model.addColumn("status");
        // Append a row

        for (Baggage ld : lld) {
            model.addRow(new Object[]{
                ld.baggageId, ld.description, ld.collor, ld.weight, ld.department, ld.materials, ld.status
            });
        }
        Container contentPane = this.getContentPane();
        contentPane.setLayout(new BorderLayout());
        contentPane.setSize(700, 500);
        contentPane.setBounds(200, 20, 700, 500);
        table.setSize(300, 150);
        JScrollPane jScrollPane1 = new JScrollPane(table);
        jScrollPane1.setSize(700, 500);
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(jScrollPane1);
        jPanel1.repaint();
        jPanel1.revalidate();

        jScrollPane1 = new JScrollPane(table);
        frame.add(jScrollPane1, BorderLayout.CENTER);
        frame.setSize(700, 500);
        frame.setVisible(true);
        frame.setLocationRelativeTo(null);
        jPanel1.removeAll();
        jPanel1.revalidate();
        jPanel1.add(EmployeeSearch);
        jPanel1.repaint();
        jPanel1.revalidate();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void Department1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Department1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Department1ActionPerformed

    private void logoutKnopMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutKnopMouseClicked
   Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_logoutKnopMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Employee().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel AddBaggage;
    private javax.swing.JLabel Background;
    private javax.swing.JLabel Backgroundlabel;
    private javax.swing.JTextField BaggageID;
    private javax.swing.JTextField Baggageid1;
    private javax.swing.JTextField Department1;
    private javax.swing.JPanel EmployeeHelp;
    private javax.swing.JPanel EmployeeHome;
    private javax.swing.JPanel EmployeeSearch;
    private javax.swing.JPanel EmployeeSumbitBaggage;
    private javax.swing.JPanel EmpolyeeAddBaggage;
    private javax.swing.JPanel Help;
    private javax.swing.JPanel Home;
    private javax.swing.JLabel IDText;
    private javax.swing.JLabel LoggedIN;
    private javax.swing.JPanel Manage;
    private javax.swing.JPanel ManageBaggagePanel;
    private javax.swing.JLabel ManageBaggagee;
    private javax.swing.JPanel Search;
    private javax.swing.JTextField SearchBaggage;
    private javax.swing.JTextField SearchBaggage1;
    private javax.swing.JTextField SearchBaggage3;
    private javax.swing.JPanel SubmitBaggage;
    private javax.swing.JLabel addBaggageButton;
    private javax.swing.JLabel addressEdit;
    private javax.swing.JLabel addressEdit1;
    private javax.swing.JTextField adress;
    private javax.swing.JTextField brand;
    private javax.swing.JTextField brand1;
    private javax.swing.JTextField city;
    private javax.swing.JLabel cityEdit;
    private javax.swing.JTextField collor;
    private javax.swing.JTextField color1;
    private javax.swing.JTextField country;
    private javax.swing.JLabel countryEdit;
    private javax.swing.JTextField department1;
    private javax.swing.JTextField description;
    private javax.swing.JTextPane description1;
    private javax.swing.JTextField email;
    private javax.swing.JLabel emailEdit;
    private javax.swing.JLabel helpButton;
    private javax.swing.JLabel homeButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JFileChooser jFileChooser1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel40;
    private javax.swing.JLabel jLabel41;
    private javax.swing.JLabel jLabel42;
    private javax.swing.JLabel jLabel43;
    private javax.swing.JLabel jLabel44;
    private javax.swing.JLabel jLabel45;
    private javax.swing.JLabel jLabel46;
    private javax.swing.JLabel jLabel47;
    private javax.swing.JLabel jLabel48;
    private javax.swing.JLabel jLabel49;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel50;
    private javax.swing.JLabel jLabel51;
    private javax.swing.JLabel jLabel52;
    private javax.swing.JLabel jLabel53;
    private javax.swing.JLabel jLabel54;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel logoutKnop;
    private javax.swing.JTextField materials;
    private javax.swing.JTextField materials1;
    private javax.swing.JPanel menu;
    private javax.swing.JTextField name;
    private javax.swing.JLabel nameEdit;
    private javax.swing.JTextField postal;
    private javax.swing.JLabel searchButton;
    private javax.swing.JTextField shippingAdress;
    private javax.swing.JLabel submitBaggageButton;
    private javax.swing.JTextField weight;
    private javax.swing.JTextField weight1;
    private javax.swing.JLabel welcomeText;
    private javax.swing.JLabel zipEdit;
    private org.jdesktop.beansbinding.BindingGroup bindingGroup;
    // End of variables declaration//GEN-END:variables

    Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
    double width = screenSize.getWidth();
    double height = screenSize.getHeight();
}
